name: Christian Ulstrup
favicon: null
layout_spectrum: 0.39189694193191826
typography_spectrum: 0.08100622752681375
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.10628296341747046
  lightness: 0.03071663505397737
  saturation: 0.3020539430435747
  rhythmicContrast: 0.32672455278225243
purpose: []
